language: php

php:
  - 7.1
  - 7.2

sudo: false

dist: trusty

before_script:
  - composer install --no-interaction --prefer-source

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit