language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - touch database/database.sqlite'
  - composer self-update
  - composer install --no-interaction --dev --prefer-source
  - php artisan key:generate


matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm


script:
  - vendor/bin/phpunit